// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/mihomo/v1/mihomo_account.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialStatus int32

const (
	CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED        CredentialStatus = 0
	CredentialStatus_CREDENTIAL_STATUS_ACTIVE             CredentialStatus = 1
	CredentialStatus_CREDENTIAL_STATUS_EXPIRED            CredentialStatus = 2
	CredentialStatus_CREDENTIAL_STATUS_INVALID            CredentialStatus = 3
	CredentialStatus_CREDENTIAL_STATUS_CHALLENGE_REQUIRED CredentialStatus = 4
)

// Enum value maps for CredentialStatus.
var (
	CredentialStatus_name = map[int32]string{
		0: "CREDENTIAL_STATUS_UNSPECIFIED",
		1: "CREDENTIAL_STATUS_ACTIVE",
		2: "CREDENTIAL_STATUS_EXPIRED",
		3: "CREDENTIAL_STATUS_INVALID",
		4: "CREDENTIAL_STATUS_CHALLENGE_REQUIRED",
	}
	CredentialStatus_value = map[string]int32{
		"CREDENTIAL_STATUS_UNSPECIFIED":        0,
		"CREDENTIAL_STATUS_ACTIVE":             1,
		"CREDENTIAL_STATUS_EXPIRED":            2,
		"CREDENTIAL_STATUS_INVALID":            3,
		"CREDENTIAL_STATUS_CHALLENGE_REQUIRED": 4,
	}
)

func (x CredentialStatus) Enum() *CredentialStatus {
	p := new(CredentialStatus)
	*p = x
	return p
}

func (x CredentialStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_mihomo_v1_mihomo_account_proto_enumTypes[0].Descriptor()
}

func (CredentialStatus) Type() protoreflect.EnumType {
	return &file_api_mihomo_v1_mihomo_account_proto_enumTypes[0]
}

func (x CredentialStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialStatus.Descriptor instead.
func (CredentialStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{0}
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceFp      string                 `protobuf:"bytes,2,opt,name=device_fp,json=deviceFp,proto3" json:"device_fp,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetDeviceFp() string {
	if x != nil {
		return x.DeviceFp
	}
	return ""
}

func (x *DeviceInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type DeviceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceFp      string                 `protobuf:"bytes,2,opt,name=device_fp,json=deviceFp,proto3" json:"device_fp,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	IsValid       bool                   `protobuf:"varint,4,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSummary) Reset() {
	*x = DeviceSummary{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSummary) ProtoMessage() {}

func (x *DeviceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSummary.ProtoReflect.Descriptor instead.
func (*DeviceSummary) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceSummary) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceSummary) GetDeviceFp() string {
	if x != nil {
		return x.DeviceFp
	}
	return ""
}

func (x *DeviceSummary) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceSummary) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *DeviceSummary) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type ProfileSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	GameBiz           string                 `protobuf:"bytes,3,opt,name=game_biz,json=gameBiz,proto3" json:"game_biz,omitempty"`
	Region            string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	PlayerId          string                 `protobuf:"bytes,5,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname          string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level             int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	IsDefault         bool                   `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProfileSummary) Reset() {
	*x = ProfileSummary{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSummary) ProtoMessage() {}

func (x *ProfileSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSummary.ProtoReflect.Descriptor instead.
func (*ProfileSummary) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileSummary) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfileSummary) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *ProfileSummary) GetGameBiz() string {
	if x != nil {
		return x.GameBiz
	}
	return ""
}

func (x *ProfileSummary) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProfileSummary) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ProfileSummary) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileSummary) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ProfileSummary) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type CredentialSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlatformAccountId string                 `protobuf:"bytes,1,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	Status            CredentialStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=mihomo.v1.CredentialStatus" json:"status,omitempty"`
	LastValidatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"last_validated_at,omitempty"`
	LastRefreshedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_refreshed_at,json=lastRefreshedAt,proto3" json:"last_refreshed_at,omitempty"`
	Devices           []*DeviceSummary       `protobuf:"bytes,5,rep,name=devices,proto3" json:"devices,omitempty"`
	Profiles          []*ProfileSummary      `protobuf:"bytes,6,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CredentialSummary) Reset() {
	*x = CredentialSummary{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialSummary) ProtoMessage() {}

func (x *CredentialSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialSummary.ProtoReflect.Descriptor instead.
func (*CredentialSummary) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{3}
}

func (x *CredentialSummary) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *CredentialSummary) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *CredentialSummary) GetLastValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastValidatedAt
	}
	return nil
}

func (x *CredentialSummary) GetLastRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRefreshedAt
	}
	return nil
}

func (x *CredentialSummary) GetDevices() []*DeviceSummary {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *CredentialSummary) GetProfiles() []*ProfileSummary {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type BindCredentialRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket    string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	CookieBundleJson string                 `protobuf:"bytes,2,opt,name=cookie_bundle_json,json=cookieBundleJson,proto3" json:"cookie_bundle_json,omitempty"`
	Device           *DeviceInfo            `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	RegionHint       string                 `protobuf:"bytes,4,opt,name=region_hint,json=regionHint,proto3" json:"region_hint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BindCredentialRequest) Reset() {
	*x = BindCredentialRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindCredentialRequest) ProtoMessage() {}

func (x *BindCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindCredentialRequest.ProtoReflect.Descriptor instead.
func (*BindCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{4}
}

func (x *BindCredentialRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *BindCredentialRequest) GetCookieBundleJson() string {
	if x != nil {
		return x.CookieBundleJson
	}
	return ""
}

func (x *BindCredentialRequest) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *BindCredentialRequest) GetRegionHint() string {
	if x != nil {
		return x.RegionHint
	}
	return ""
}

type BindCredentialResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlatformAccountId string                 `protobuf:"bytes,1,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	Status            CredentialStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=mihomo.v1.CredentialStatus" json:"status,omitempty"`
	Profiles          []*ProfileSummary      `protobuf:"bytes,3,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BindCredentialResponse) Reset() {
	*x = BindCredentialResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindCredentialResponse) ProtoMessage() {}

func (x *BindCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindCredentialResponse.ProtoReflect.Descriptor instead.
func (*BindCredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{5}
}

func (x *BindCredentialResponse) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *BindCredentialResponse) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *BindCredentialResponse) GetProfiles() []*ProfileSummary {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type UpsertDeviceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	Device            *DeviceInfo            `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertDeviceRequest) Reset() {
	*x = UpsertDeviceRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeviceRequest) ProtoMessage() {}

func (x *UpsertDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpsertDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertDeviceRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *UpsertDeviceRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *UpsertDeviceRequest) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

type UpsertDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDeviceResponse) Reset() {
	*x = UpsertDeviceResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeviceResponse) ProtoMessage() {}

func (x *UpsertDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpsertDeviceResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConfirmPrimaryProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	PlayerId          string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfirmPrimaryProfileRequest) Reset() {
	*x = ConfirmPrimaryProfileRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPrimaryProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPrimaryProfileRequest) ProtoMessage() {}

func (x *ConfirmPrimaryProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPrimaryProfileRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPrimaryProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmPrimaryProfileRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *ConfirmPrimaryProfileRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *ConfirmPrimaryProfileRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ConfirmPrimaryProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ProfileSummary        `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPrimaryProfileResponse) Reset() {
	*x = ConfirmPrimaryProfileResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPrimaryProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPrimaryProfileResponse) ProtoMessage() {}

func (x *ConfirmPrimaryProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPrimaryProfileResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPrimaryProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmPrimaryProfileResponse) GetProfile() *ProfileSummary {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetCredentialStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCredentialStatusRequest) Reset() {
	*x = GetCredentialStatusRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialStatusRequest) ProtoMessage() {}

func (x *GetCredentialStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{10}
}

func (x *GetCredentialStatusRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *GetCredentialStatusRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

type GetCredentialStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          CredentialStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=mihomo.v1.CredentialStatus" json:"status,omitempty"`
	LastValidatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"last_validated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCredentialStatusResponse) Reset() {
	*x = GetCredentialStatusResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialStatusResponse) ProtoMessage() {}

func (x *GetCredentialStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{11}
}

func (x *GetCredentialStatusResponse) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *GetCredentialStatusResponse) GetLastValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastValidatedAt
	}
	return nil
}

type ValidateCredentialRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidateCredentialRequest) Reset() {
	*x = ValidateCredentialRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCredentialRequest) ProtoMessage() {}

func (x *ValidateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCredentialRequest.ProtoReflect.Descriptor instead.
func (*ValidateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateCredentialRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *ValidateCredentialRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

type ValidateCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CredentialStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=mihomo.v1.CredentialStatus" json:"status,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCredentialResponse) Reset() {
	*x = ValidateCredentialResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCredentialResponse) ProtoMessage() {}

func (x *ValidateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCredentialResponse.ProtoReflect.Descriptor instead.
func (*ValidateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateCredentialResponse) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *ValidateCredentialResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type RefreshCredentialRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RefreshCredentialRequest) Reset() {
	*x = RefreshCredentialRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCredentialRequest) ProtoMessage() {}

func (x *RefreshCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCredentialRequest.ProtoReflect.Descriptor instead.
func (*RefreshCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshCredentialRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *RefreshCredentialRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

type RefreshCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CredentialStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=mihomo.v1.CredentialStatus" json:"status,omitempty"`
	RefreshedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=refreshed_at,json=refreshedAt,proto3" json:"refreshed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshCredentialResponse) Reset() {
	*x = RefreshCredentialResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCredentialResponse) ProtoMessage() {}

func (x *RefreshCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCredentialResponse.ProtoReflect.Descriptor instead.
func (*RefreshCredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{15}
}

func (x *RefreshCredentialResponse) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *RefreshCredentialResponse) GetRefreshedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshedAt
	}
	return nil
}

type ListProfilesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{16}
}

func (x *ListProfilesRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *ListProfilesRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*ProfileSummary      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{17}
}

func (x *ListProfilesResponse) GetProfiles() []*ProfileSummary {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type GetPrimaryProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPrimaryProfileRequest) Reset() {
	*x = GetPrimaryProfileRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrimaryProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrimaryProfileRequest) ProtoMessage() {}

func (x *GetPrimaryProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrimaryProfileRequest.ProtoReflect.Descriptor instead.
func (*GetPrimaryProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{18}
}

func (x *GetPrimaryProfileRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *GetPrimaryProfileRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

type GetPrimaryProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ProfileSummary        `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrimaryProfileResponse) Reset() {
	*x = GetPrimaryProfileResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrimaryProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrimaryProfileResponse) ProtoMessage() {}

func (x *GetPrimaryProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrimaryProfileResponse.ProtoReflect.Descriptor instead.
func (*GetPrimaryProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{19}
}

func (x *GetPrimaryProfileResponse) GetProfile() *ProfileSummary {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetAuthKeyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	PlayerId          string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAuthKeyRequest) Reset() {
	*x = GetAuthKeyRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthKeyRequest) ProtoMessage() {}

func (x *GetAuthKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAuthKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{20}
}

func (x *GetAuthKeyRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *GetAuthKeyRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *GetAuthKeyRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetAuthKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authkey       string                 `protobuf:"bytes,1,opt,name=authkey,proto3" json:"authkey,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthKeyResponse) Reset() {
	*x = GetAuthKeyResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthKeyResponse) ProtoMessage() {}

func (x *GetAuthKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAuthKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{21}
}

func (x *GetAuthKeyResponse) GetAuthkey() string {
	if x != nil {
		return x.Authkey
	}
	return ""
}

func (x *GetAuthKeyResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetCredentialSummaryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCredentialSummaryRequest) Reset() {
	*x = GetCredentialSummaryRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialSummaryRequest) ProtoMessage() {}

func (x *GetCredentialSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialSummaryRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{22}
}

func (x *GetCredentialSummaryRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *GetCredentialSummaryRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

type GetCredentialSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *CredentialSummary     `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialSummaryResponse) Reset() {
	*x = GetCredentialSummaryResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialSummaryResponse) ProtoMessage() {}

func (x *GetCredentialSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialSummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{23}
}

func (x *GetCredentialSummaryResponse) GetSummary() *CredentialSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type UpdateCredentialRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	CookieBundleJson  string                 `protobuf:"bytes,3,opt,name=cookie_bundle_json,json=cookieBundleJson,proto3" json:"cookie_bundle_json,omitempty"`
	Device            *DeviceInfo            `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	RegionHint        string                 `protobuf:"bytes,5,opt,name=region_hint,json=regionHint,proto3" json:"region_hint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateCredentialRequest) Reset() {
	*x = UpdateCredentialRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCredentialRequest) ProtoMessage() {}

func (x *UpdateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCredentialRequest.ProtoReflect.Descriptor instead.
func (*UpdateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateCredentialRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *UpdateCredentialRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *UpdateCredentialRequest) GetCookieBundleJson() string {
	if x != nil {
		return x.CookieBundleJson
	}
	return ""
}

func (x *UpdateCredentialRequest) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *UpdateCredentialRequest) GetRegionHint() string {
	if x != nil {
		return x.RegionHint
	}
	return ""
}

type UpdateCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *CredentialSummary     `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCredentialResponse) Reset() {
	*x = UpdateCredentialResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCredentialResponse) ProtoMessage() {}

func (x *UpdateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCredentialResponse.ProtoReflect.Descriptor instead.
func (*UpdateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateCredentialResponse) GetSummary() *CredentialSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type DeleteCredentialRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceTicket     string                 `protobuf:"bytes,1,opt,name=service_ticket,json=serviceTicket,proto3" json:"service_ticket,omitempty"`
	PlatformAccountId string                 `protobuf:"bytes,2,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteCredentialRequest) Reset() {
	*x = DeleteCredentialRequest{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialRequest) ProtoMessage() {}

func (x *DeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteCredentialRequest) GetServiceTicket() string {
	if x != nil {
		return x.ServiceTicket
	}
	return ""
}

func (x *DeleteCredentialRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

type DeleteCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialResponse) Reset() {
	*x = DeleteCredentialResponse{}
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialResponse) ProtoMessage() {}

func (x *DeleteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mihomo_v1_mihomo_account_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_mihomo_v1_mihomo_account_proto protoreflect.FileDescriptor

const file_api_mihomo_v1_mihomo_account_proto_rawDesc = "" +
	"\n" +
	"\"api/mihomo/v1/mihomo_account.proto\x12\tmihomo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tdevice_fp\x18\x02 \x01(\tR\bdeviceFp\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\"\xc3\x01\n" +
	"\rDeviceSummary\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tdevice_fp\x18\x02 \x01(\tR\bdeviceFp\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x19\n" +
	"\bis_valid\x18\x04 \x01(\bR\aisValid\x12<\n" +
	"\flast_seen_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"\xf1\x01\n" +
	"\x0eProfileSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\x12\x19\n" +
	"\bgame_biz\x18\x03 \x01(\tR\agameBiz\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1b\n" +
	"\tplayer_id\x18\x05 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"is_default\x18\b \x01(\bR\tisDefault\"\xf3\x02\n" +
	"\x11CredentialSummary\x12.\n" +
	"\x13platform_account_id\x18\x01 \x01(\tR\x11platformAccountId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.mihomo.v1.CredentialStatusR\x06status\x12F\n" +
	"\x11last_validated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastValidatedAt\x12F\n" +
	"\x11last_refreshed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastRefreshedAt\x122\n" +
	"\adevices\x18\x05 \x03(\v2\x18.mihomo.v1.DeviceSummaryR\adevices\x125\n" +
	"\bprofiles\x18\x06 \x03(\v2\x19.mihomo.v1.ProfileSummaryR\bprofiles\"\xbc\x01\n" +
	"\x15BindCredentialRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12,\n" +
	"\x12cookie_bundle_json\x18\x02 \x01(\tR\x10cookieBundleJson\x12-\n" +
	"\x06device\x18\x03 \x01(\v2\x15.mihomo.v1.DeviceInfoR\x06device\x12\x1f\n" +
	"\vregion_hint\x18\x04 \x01(\tR\n" +
	"regionHint\"\xb4\x01\n" +
	"\x16BindCredentialResponse\x12.\n" +
	"\x13platform_account_id\x18\x01 \x01(\tR\x11platformAccountId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.mihomo.v1.CredentialStatusR\x06status\x125\n" +
	"\bprofiles\x18\x03 \x03(\v2\x19.mihomo.v1.ProfileSummaryR\bprofiles\"\x9b\x01\n" +
	"\x13UpsertDeviceRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\x12-\n" +
	"\x06device\x18\x03 \x01(\v2\x15.mihomo.v1.DeviceInfoR\x06device\"0\n" +
	"\x14UpsertDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x92\x01\n" +
	"\x1cConfirmPrimaryProfileRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\"T\n" +
	"\x1dConfirmPrimaryProfileResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.mihomo.v1.ProfileSummaryR\aprofile\"s\n" +
	"\x1aGetCredentialStatusRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\"\x9a\x01\n" +
	"\x1bGetCredentialStatusResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.mihomo.v1.CredentialStatusR\x06status\x12F\n" +
	"\x11last_validated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastValidatedAt\"r\n" +
	"\x19ValidateCredentialRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\"p\n" +
	"\x1aValidateCredentialResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.mihomo.v1.CredentialStatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\"q\n" +
	"\x18RefreshCredentialRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\"\x8f\x01\n" +
	"\x19RefreshCredentialResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.mihomo.v1.CredentialStatusR\x06status\x12=\n" +
	"\frefreshed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vrefreshedAt\"l\n" +
	"\x13ListProfilesRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\"M\n" +
	"\x14ListProfilesResponse\x125\n" +
	"\bprofiles\x18\x01 \x03(\v2\x19.mihomo.v1.ProfileSummaryR\bprofiles\"q\n" +
	"\x18GetPrimaryProfileRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\"P\n" +
	"\x19GetPrimaryProfileResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.mihomo.v1.ProfileSummaryR\aprofile\"\x87\x01\n" +
	"\x11GetAuthKeyRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\"i\n" +
	"\x12GetAuthKeyResponse\x12\x18\n" +
	"\aauthkey\x18\x01 \x01(\tR\aauthkey\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"t\n" +
	"\x1bGetCredentialSummaryRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\"V\n" +
	"\x1cGetCredentialSummaryResponse\x126\n" +
	"\asummary\x18\x01 \x01(\v2\x1c.mihomo.v1.CredentialSummaryR\asummary\"\xee\x01\n" +
	"\x17UpdateCredentialRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\x12,\n" +
	"\x12cookie_bundle_json\x18\x03 \x01(\tR\x10cookieBundleJson\x12-\n" +
	"\x06device\x18\x04 \x01(\v2\x15.mihomo.v1.DeviceInfoR\x06device\x12\x1f\n" +
	"\vregion_hint\x18\x05 \x01(\tR\n" +
	"regionHint\"R\n" +
	"\x18UpdateCredentialResponse\x126\n" +
	"\asummary\x18\x01 \x01(\v2\x1c.mihomo.v1.CredentialSummaryR\asummary\"p\n" +
	"\x17DeleteCredentialRequest\x12%\n" +
	"\x0eservice_ticket\x18\x01 \x01(\tR\rserviceTicket\x12.\n" +
	"\x13platform_account_id\x18\x02 \x01(\tR\x11platformAccountId\"4\n" +
	"\x18DeleteCredentialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xbb\x01\n" +
	"\x10CredentialStatus\x12!\n" +
	"\x1dCREDENTIAL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CREDENTIAL_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19CREDENTIAL_STATUS_EXPIRED\x10\x02\x12\x1d\n" +
	"\x19CREDENTIAL_STATUS_INVALID\x10\x03\x12(\n" +
	"$CREDENTIAL_STATUS_CHALLENGE_REQUIRED\x10\x042\xf2\b\n" +
	"\x14MihomoAccountService\x12U\n" +
	"\x0eBindCredential\x12 .mihomo.v1.BindCredentialRequest\x1a!.mihomo.v1.BindCredentialResponse\x12O\n" +
	"\fUpsertDevice\x12\x1e.mihomo.v1.UpsertDeviceRequest\x1a\x1f.mihomo.v1.UpsertDeviceResponse\x12j\n" +
	"\x15ConfirmPrimaryProfile\x12'.mihomo.v1.ConfirmPrimaryProfileRequest\x1a(.mihomo.v1.ConfirmPrimaryProfileResponse\x12d\n" +
	"\x13GetCredentialStatus\x12%.mihomo.v1.GetCredentialStatusRequest\x1a&.mihomo.v1.GetCredentialStatusResponse\x12a\n" +
	"\x12ValidateCredential\x12$.mihomo.v1.ValidateCredentialRequest\x1a%.mihomo.v1.ValidateCredentialResponse\x12^\n" +
	"\x11RefreshCredential\x12#.mihomo.v1.RefreshCredentialRequest\x1a$.mihomo.v1.RefreshCredentialResponse\x12O\n" +
	"\fListProfiles\x12\x1e.mihomo.v1.ListProfilesRequest\x1a\x1f.mihomo.v1.ListProfilesResponse\x12^\n" +
	"\x11GetPrimaryProfile\x12#.mihomo.v1.GetPrimaryProfileRequest\x1a$.mihomo.v1.GetPrimaryProfileResponse\x12I\n" +
	"\n" +
	"GetAuthKey\x12\x1c.mihomo.v1.GetAuthKeyRequest\x1a\x1d.mihomo.v1.GetAuthKeyResponse\x12g\n" +
	"\x14GetCredentialSummary\x12&.mihomo.v1.GetCredentialSummaryRequest\x1a'.mihomo.v1.GetCredentialSummaryResponse\x12[\n" +
	"\x10UpdateCredential\x12\".mihomo.v1.UpdateCredentialRequest\x1a#.mihomo.v1.UpdateCredentialResponse\x12[\n" +
	"\x10DeleteCredential\x12\".mihomo.v1.DeleteCredentialRequest\x1a#.mihomo.v1.DeleteCredentialResponseB*Z(platform-mihomo-service/api/mihomo/v1;v1b\x06proto3"

var (
	file_api_mihomo_v1_mihomo_account_proto_rawDescOnce sync.Once
	file_api_mihomo_v1_mihomo_account_proto_rawDescData []byte
)

func file_api_mihomo_v1_mihomo_account_proto_rawDescGZIP() []byte {
	file_api_mihomo_v1_mihomo_account_proto_rawDescOnce.Do(func() {
		file_api_mihomo_v1_mihomo_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mihomo_v1_mihomo_account_proto_rawDesc), len(file_api_mihomo_v1_mihomo_account_proto_rawDesc)))
	})
	return file_api_mihomo_v1_mihomo_account_proto_rawDescData
}

var file_api_mihomo_v1_mihomo_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_mihomo_v1_mihomo_account_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_mihomo_v1_mihomo_account_proto_goTypes = []any{
	(CredentialStatus)(0),                 // 0: mihomo.v1.CredentialStatus
	(*DeviceInfo)(nil),                    // 1: mihomo.v1.DeviceInfo
	(*DeviceSummary)(nil),                 // 2: mihomo.v1.DeviceSummary
	(*ProfileSummary)(nil),                // 3: mihomo.v1.ProfileSummary
	(*CredentialSummary)(nil),             // 4: mihomo.v1.CredentialSummary
	(*BindCredentialRequest)(nil),         // 5: mihomo.v1.BindCredentialRequest
	(*BindCredentialResponse)(nil),        // 6: mihomo.v1.BindCredentialResponse
	(*UpsertDeviceRequest)(nil),           // 7: mihomo.v1.UpsertDeviceRequest
	(*UpsertDeviceResponse)(nil),          // 8: mihomo.v1.UpsertDeviceResponse
	(*ConfirmPrimaryProfileRequest)(nil),  // 9: mihomo.v1.ConfirmPrimaryProfileRequest
	(*ConfirmPrimaryProfileResponse)(nil), // 10: mihomo.v1.ConfirmPrimaryProfileResponse
	(*GetCredentialStatusRequest)(nil),    // 11: mihomo.v1.GetCredentialStatusRequest
	(*GetCredentialStatusResponse)(nil),   // 12: mihomo.v1.GetCredentialStatusResponse
	(*ValidateCredentialRequest)(nil),     // 13: mihomo.v1.ValidateCredentialRequest
	(*ValidateCredentialResponse)(nil),    // 14: mihomo.v1.ValidateCredentialResponse
	(*RefreshCredentialRequest)(nil),      // 15: mihomo.v1.RefreshCredentialRequest
	(*RefreshCredentialResponse)(nil),     // 16: mihomo.v1.RefreshCredentialResponse
	(*ListProfilesRequest)(nil),           // 17: mihomo.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),          // 18: mihomo.v1.ListProfilesResponse
	(*GetPrimaryProfileRequest)(nil),      // 19: mihomo.v1.GetPrimaryProfileRequest
	(*GetPrimaryProfileResponse)(nil),     // 20: mihomo.v1.GetPrimaryProfileResponse
	(*GetAuthKeyRequest)(nil),             // 21: mihomo.v1.GetAuthKeyRequest
	(*GetAuthKeyResponse)(nil),            // 22: mihomo.v1.GetAuthKeyResponse
	(*GetCredentialSummaryRequest)(nil),   // 23: mihomo.v1.GetCredentialSummaryRequest
	(*GetCredentialSummaryResponse)(nil),  // 24: mihomo.v1.GetCredentialSummaryResponse
	(*UpdateCredentialRequest)(nil),       // 25: mihomo.v1.UpdateCredentialRequest
	(*UpdateCredentialResponse)(nil),      // 26: mihomo.v1.UpdateCredentialResponse
	(*DeleteCredentialRequest)(nil),       // 27: mihomo.v1.DeleteCredentialRequest
	(*DeleteCredentialResponse)(nil),      // 28: mihomo.v1.DeleteCredentialResponse
	(*timestamppb.Timestamp)(nil),         // 29: google.protobuf.Timestamp
}
var file_api_mihomo_v1_mihomo_account_proto_depIdxs = []int32{
	29, // 0: mihomo.v1.DeviceSummary.last_seen_at:type_name -> google.protobuf.Timestamp
	0,  // 1: mihomo.v1.CredentialSummary.status:type_name -> mihomo.v1.CredentialStatus
	29, // 2: mihomo.v1.CredentialSummary.last_validated_at:type_name -> google.protobuf.Timestamp
	29, // 3: mihomo.v1.CredentialSummary.last_refreshed_at:type_name -> google.protobuf.Timestamp
	2,  // 4: mihomo.v1.CredentialSummary.devices:type_name -> mihomo.v1.DeviceSummary
	3,  // 5: mihomo.v1.CredentialSummary.profiles:type_name -> mihomo.v1.ProfileSummary
	1,  // 6: mihomo.v1.BindCredentialRequest.device:type_name -> mihomo.v1.DeviceInfo
	0,  // 7: mihomo.v1.BindCredentialResponse.status:type_name -> mihomo.v1.CredentialStatus
	3,  // 8: mihomo.v1.BindCredentialResponse.profiles:type_name -> mihomo.v1.ProfileSummary
	1,  // 9: mihomo.v1.UpsertDeviceRequest.device:type_name -> mihomo.v1.DeviceInfo
	3,  // 10: mihomo.v1.ConfirmPrimaryProfileResponse.profile:type_name -> mihomo.v1.ProfileSummary
	0,  // 11: mihomo.v1.GetCredentialStatusResponse.status:type_name -> mihomo.v1.CredentialStatus
	29, // 12: mihomo.v1.GetCredentialStatusResponse.last_validated_at:type_name -> google.protobuf.Timestamp
	0,  // 13: mihomo.v1.ValidateCredentialResponse.status:type_name -> mihomo.v1.CredentialStatus
	0,  // 14: mihomo.v1.RefreshCredentialResponse.status:type_name -> mihomo.v1.CredentialStatus
	29, // 15: mihomo.v1.RefreshCredentialResponse.refreshed_at:type_name -> google.protobuf.Timestamp
	3,  // 16: mihomo.v1.ListProfilesResponse.profiles:type_name -> mihomo.v1.ProfileSummary
	3,  // 17: mihomo.v1.GetPrimaryProfileResponse.profile:type_name -> mihomo.v1.ProfileSummary
	29, // 18: mihomo.v1.GetAuthKeyResponse.expires_at:type_name -> google.protobuf.Timestamp
	4,  // 19: mihomo.v1.GetCredentialSummaryResponse.summary:type_name -> mihomo.v1.CredentialSummary
	1,  // 20: mihomo.v1.UpdateCredentialRequest.device:type_name -> mihomo.v1.DeviceInfo
	4,  // 21: mihomo.v1.UpdateCredentialResponse.summary:type_name -> mihomo.v1.CredentialSummary
	5,  // 22: mihomo.v1.MihomoAccountService.BindCredential:input_type -> mihomo.v1.BindCredentialRequest
	7,  // 23: mihomo.v1.MihomoAccountService.UpsertDevice:input_type -> mihomo.v1.UpsertDeviceRequest
	9,  // 24: mihomo.v1.MihomoAccountService.ConfirmPrimaryProfile:input_type -> mihomo.v1.ConfirmPrimaryProfileRequest
	11, // 25: mihomo.v1.MihomoAccountService.GetCredentialStatus:input_type -> mihomo.v1.GetCredentialStatusRequest
	13, // 26: mihomo.v1.MihomoAccountService.ValidateCredential:input_type -> mihomo.v1.ValidateCredentialRequest
	15, // 27: mihomo.v1.MihomoAccountService.RefreshCredential:input_type -> mihomo.v1.RefreshCredentialRequest
	17, // 28: mihomo.v1.MihomoAccountService.ListProfiles:input_type -> mihomo.v1.ListProfilesRequest
	19, // 29: mihomo.v1.MihomoAccountService.GetPrimaryProfile:input_type -> mihomo.v1.GetPrimaryProfileRequest
	21, // 30: mihomo.v1.MihomoAccountService.GetAuthKey:input_type -> mihomo.v1.GetAuthKeyRequest
	23, // 31: mihomo.v1.MihomoAccountService.GetCredentialSummary:input_type -> mihomo.v1.GetCredentialSummaryRequest
	25, // 32: mihomo.v1.MihomoAccountService.UpdateCredential:input_type -> mihomo.v1.UpdateCredentialRequest
	27, // 33: mihomo.v1.MihomoAccountService.DeleteCredential:input_type -> mihomo.v1.DeleteCredentialRequest
	6,  // 34: mihomo.v1.MihomoAccountService.BindCredential:output_type -> mihomo.v1.BindCredentialResponse
	8,  // 35: mihomo.v1.MihomoAccountService.UpsertDevice:output_type -> mihomo.v1.UpsertDeviceResponse
	10, // 36: mihomo.v1.MihomoAccountService.ConfirmPrimaryProfile:output_type -> mihomo.v1.ConfirmPrimaryProfileResponse
	12, // 37: mihomo.v1.MihomoAccountService.GetCredentialStatus:output_type -> mihomo.v1.GetCredentialStatusResponse
	14, // 38: mihomo.v1.MihomoAccountService.ValidateCredential:output_type -> mihomo.v1.ValidateCredentialResponse
	16, // 39: mihomo.v1.MihomoAccountService.RefreshCredential:output_type -> mihomo.v1.RefreshCredentialResponse
	18, // 40: mihomo.v1.MihomoAccountService.ListProfiles:output_type -> mihomo.v1.ListProfilesResponse
	20, // 41: mihomo.v1.MihomoAccountService.GetPrimaryProfile:output_type -> mihomo.v1.GetPrimaryProfileResponse
	22, // 42: mihomo.v1.MihomoAccountService.GetAuthKey:output_type -> mihomo.v1.GetAuthKeyResponse
	24, // 43: mihomo.v1.MihomoAccountService.GetCredentialSummary:output_type -> mihomo.v1.GetCredentialSummaryResponse
	26, // 44: mihomo.v1.MihomoAccountService.UpdateCredential:output_type -> mihomo.v1.UpdateCredentialResponse
	28, // 45: mihomo.v1.MihomoAccountService.DeleteCredential:output_type -> mihomo.v1.DeleteCredentialResponse
	34, // [34:46] is the sub-list for method output_type
	22, // [22:34] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_mihomo_v1_mihomo_account_proto_init() }
func file_api_mihomo_v1_mihomo_account_proto_init() {
	if File_api_mihomo_v1_mihomo_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mihomo_v1_mihomo_account_proto_rawDesc), len(file_api_mihomo_v1_mihomo_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mihomo_v1_mihomo_account_proto_goTypes,
		DependencyIndexes: file_api_mihomo_v1_mihomo_account_proto_depIdxs,
		EnumInfos:         file_api_mihomo_v1_mihomo_account_proto_enumTypes,
		MessageInfos:      file_api_mihomo_v1_mihomo_account_proto_msgTypes,
	}.Build()
	File_api_mihomo_v1_mihomo_account_proto = out.File
	file_api_mihomo_v1_mihomo_account_proto_goTypes = nil
	file_api_mihomo_v1_mihomo_account_proto_depIdxs = nil
}
