// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/mihomo/v1/mihomo_account.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MihomoAccountService_BindCredential_FullMethodName        = "/mihomo.v1.MihomoAccountService/BindCredential"
	MihomoAccountService_UpsertDevice_FullMethodName          = "/mihomo.v1.MihomoAccountService/UpsertDevice"
	MihomoAccountService_ConfirmPrimaryProfile_FullMethodName = "/mihomo.v1.MihomoAccountService/ConfirmPrimaryProfile"
	MihomoAccountService_GetCredentialStatus_FullMethodName   = "/mihomo.v1.MihomoAccountService/GetCredentialStatus"
	MihomoAccountService_ValidateCredential_FullMethodName    = "/mihomo.v1.MihomoAccountService/ValidateCredential"
	MihomoAccountService_RefreshCredential_FullMethodName     = "/mihomo.v1.MihomoAccountService/RefreshCredential"
	MihomoAccountService_ListProfiles_FullMethodName          = "/mihomo.v1.MihomoAccountService/ListProfiles"
	MihomoAccountService_GetPrimaryProfile_FullMethodName     = "/mihomo.v1.MihomoAccountService/GetPrimaryProfile"
	MihomoAccountService_GetAuthKey_FullMethodName            = "/mihomo.v1.MihomoAccountService/GetAuthKey"
	MihomoAccountService_GetCredentialSummary_FullMethodName  = "/mihomo.v1.MihomoAccountService/GetCredentialSummary"
	MihomoAccountService_UpdateCredential_FullMethodName      = "/mihomo.v1.MihomoAccountService/UpdateCredential"
	MihomoAccountService_DeleteCredential_FullMethodName      = "/mihomo.v1.MihomoAccountService/DeleteCredential"
)

// MihomoAccountServiceClient is the client API for MihomoAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MihomoAccountServiceClient interface {
	BindCredential(ctx context.Context, in *BindCredentialRequest, opts ...grpc.CallOption) (*BindCredentialResponse, error)
	UpsertDevice(ctx context.Context, in *UpsertDeviceRequest, opts ...grpc.CallOption) (*UpsertDeviceResponse, error)
	ConfirmPrimaryProfile(ctx context.Context, in *ConfirmPrimaryProfileRequest, opts ...grpc.CallOption) (*ConfirmPrimaryProfileResponse, error)
	GetCredentialStatus(ctx context.Context, in *GetCredentialStatusRequest, opts ...grpc.CallOption) (*GetCredentialStatusResponse, error)
	ValidateCredential(ctx context.Context, in *ValidateCredentialRequest, opts ...grpc.CallOption) (*ValidateCredentialResponse, error)
	RefreshCredential(ctx context.Context, in *RefreshCredentialRequest, opts ...grpc.CallOption) (*RefreshCredentialResponse, error)
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	GetPrimaryProfile(ctx context.Context, in *GetPrimaryProfileRequest, opts ...grpc.CallOption) (*GetPrimaryProfileResponse, error)
	GetAuthKey(ctx context.Context, in *GetAuthKeyRequest, opts ...grpc.CallOption) (*GetAuthKeyResponse, error)
	GetCredentialSummary(ctx context.Context, in *GetCredentialSummaryRequest, opts ...grpc.CallOption) (*GetCredentialSummaryResponse, error)
	UpdateCredential(ctx context.Context, in *UpdateCredentialRequest, opts ...grpc.CallOption) (*UpdateCredentialResponse, error)
	DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error)
}

type mihomoAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMihomoAccountServiceClient(cc grpc.ClientConnInterface) MihomoAccountServiceClient {
	return &mihomoAccountServiceClient{cc}
}

func (c *mihomoAccountServiceClient) BindCredential(ctx context.Context, in *BindCredentialRequest, opts ...grpc.CallOption) (*BindCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindCredentialResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_BindCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) UpsertDevice(ctx context.Context, in *UpsertDeviceRequest, opts ...grpc.CallOption) (*UpsertDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertDeviceResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_UpsertDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) ConfirmPrimaryProfile(ctx context.Context, in *ConfirmPrimaryProfileRequest, opts ...grpc.CallOption) (*ConfirmPrimaryProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPrimaryProfileResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_ConfirmPrimaryProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) GetCredentialStatus(ctx context.Context, in *GetCredentialStatusRequest, opts ...grpc.CallOption) (*GetCredentialStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialStatusResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_GetCredentialStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) ValidateCredential(ctx context.Context, in *ValidateCredentialRequest, opts ...grpc.CallOption) (*ValidateCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCredentialResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_ValidateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) RefreshCredential(ctx context.Context, in *RefreshCredentialRequest, opts ...grpc.CallOption) (*RefreshCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshCredentialResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_RefreshCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) GetPrimaryProfile(ctx context.Context, in *GetPrimaryProfileRequest, opts ...grpc.CallOption) (*GetPrimaryProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrimaryProfileResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_GetPrimaryProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) GetAuthKey(ctx context.Context, in *GetAuthKeyRequest, opts ...grpc.CallOption) (*GetAuthKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthKeyResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_GetAuthKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) GetCredentialSummary(ctx context.Context, in *GetCredentialSummaryRequest, opts ...grpc.CallOption) (*GetCredentialSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialSummaryResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_GetCredentialSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) UpdateCredential(ctx context.Context, in *UpdateCredentialRequest, opts ...grpc.CallOption) (*UpdateCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCredentialResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_UpdateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoAccountServiceClient) DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCredentialResponse)
	err := c.cc.Invoke(ctx, MihomoAccountService_DeleteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MihomoAccountServiceServer is the server API for MihomoAccountService service.
// All implementations must embed UnimplementedMihomoAccountServiceServer
// for forward compatibility.
type MihomoAccountServiceServer interface {
	BindCredential(context.Context, *BindCredentialRequest) (*BindCredentialResponse, error)
	UpsertDevice(context.Context, *UpsertDeviceRequest) (*UpsertDeviceResponse, error)
	ConfirmPrimaryProfile(context.Context, *ConfirmPrimaryProfileRequest) (*ConfirmPrimaryProfileResponse, error)
	GetCredentialStatus(context.Context, *GetCredentialStatusRequest) (*GetCredentialStatusResponse, error)
	ValidateCredential(context.Context, *ValidateCredentialRequest) (*ValidateCredentialResponse, error)
	RefreshCredential(context.Context, *RefreshCredentialRequest) (*RefreshCredentialResponse, error)
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	GetPrimaryProfile(context.Context, *GetPrimaryProfileRequest) (*GetPrimaryProfileResponse, error)
	GetAuthKey(context.Context, *GetAuthKeyRequest) (*GetAuthKeyResponse, error)
	GetCredentialSummary(context.Context, *GetCredentialSummaryRequest) (*GetCredentialSummaryResponse, error)
	UpdateCredential(context.Context, *UpdateCredentialRequest) (*UpdateCredentialResponse, error)
	DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error)
	mustEmbedUnimplementedMihomoAccountServiceServer()
}

// UnimplementedMihomoAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMihomoAccountServiceServer struct{}

func (UnimplementedMihomoAccountServiceServer) BindCredential(context.Context, *BindCredentialRequest) (*BindCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindCredential not implemented")
}
func (UnimplementedMihomoAccountServiceServer) UpsertDevice(context.Context, *UpsertDeviceRequest) (*UpsertDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertDevice not implemented")
}
func (UnimplementedMihomoAccountServiceServer) ConfirmPrimaryProfile(context.Context, *ConfirmPrimaryProfileRequest) (*ConfirmPrimaryProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPrimaryProfile not implemented")
}
func (UnimplementedMihomoAccountServiceServer) GetCredentialStatus(context.Context, *GetCredentialStatusRequest) (*GetCredentialStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentialStatus not implemented")
}
func (UnimplementedMihomoAccountServiceServer) ValidateCredential(context.Context, *ValidateCredentialRequest) (*ValidateCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCredential not implemented")
}
func (UnimplementedMihomoAccountServiceServer) RefreshCredential(context.Context, *RefreshCredentialRequest) (*RefreshCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshCredential not implemented")
}
func (UnimplementedMihomoAccountServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedMihomoAccountServiceServer) GetPrimaryProfile(context.Context, *GetPrimaryProfileRequest) (*GetPrimaryProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrimaryProfile not implemented")
}
func (UnimplementedMihomoAccountServiceServer) GetAuthKey(context.Context, *GetAuthKeyRequest) (*GetAuthKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthKey not implemented")
}
func (UnimplementedMihomoAccountServiceServer) GetCredentialSummary(context.Context, *GetCredentialSummaryRequest) (*GetCredentialSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentialSummary not implemented")
}
func (UnimplementedMihomoAccountServiceServer) UpdateCredential(context.Context, *UpdateCredentialRequest) (*UpdateCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCredential not implemented")
}
func (UnimplementedMihomoAccountServiceServer) DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCredential not implemented")
}
func (UnimplementedMihomoAccountServiceServer) mustEmbedUnimplementedMihomoAccountServiceServer() {}
func (UnimplementedMihomoAccountServiceServer) testEmbeddedByValue()                              {}

// UnsafeMihomoAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MihomoAccountServiceServer will
// result in compilation errors.
type UnsafeMihomoAccountServiceServer interface {
	mustEmbedUnimplementedMihomoAccountServiceServer()
}

func RegisterMihomoAccountServiceServer(s grpc.ServiceRegistrar, srv MihomoAccountServiceServer) {
	// If the following call panics, it indicates UnimplementedMihomoAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MihomoAccountService_ServiceDesc, srv)
}

func _MihomoAccountService_BindCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).BindCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_BindCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).BindCredential(ctx, req.(*BindCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_UpsertDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).UpsertDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_UpsertDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).UpsertDevice(ctx, req.(*UpsertDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_ConfirmPrimaryProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPrimaryProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).ConfirmPrimaryProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_ConfirmPrimaryProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).ConfirmPrimaryProfile(ctx, req.(*ConfirmPrimaryProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_GetCredentialStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).GetCredentialStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_GetCredentialStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).GetCredentialStatus(ctx, req.(*GetCredentialStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_ValidateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).ValidateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_ValidateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).ValidateCredential(ctx, req.(*ValidateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_RefreshCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).RefreshCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_RefreshCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).RefreshCredential(ctx, req.(*RefreshCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_GetPrimaryProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrimaryProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).GetPrimaryProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_GetPrimaryProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).GetPrimaryProfile(ctx, req.(*GetPrimaryProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_GetAuthKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).GetAuthKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_GetAuthKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).GetAuthKey(ctx, req.(*GetAuthKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_GetCredentialSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).GetCredentialSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_GetCredentialSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).GetCredentialSummary(ctx, req.(*GetCredentialSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_UpdateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).UpdateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_UpdateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).UpdateCredential(ctx, req.(*UpdateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoAccountService_DeleteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoAccountServiceServer).DeleteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoAccountService_DeleteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoAccountServiceServer).DeleteCredential(ctx, req.(*DeleteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MihomoAccountService_ServiceDesc is the grpc.ServiceDesc for MihomoAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MihomoAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mihomo.v1.MihomoAccountService",
	HandlerType: (*MihomoAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BindCredential",
			Handler:    _MihomoAccountService_BindCredential_Handler,
		},
		{
			MethodName: "UpsertDevice",
			Handler:    _MihomoAccountService_UpsertDevice_Handler,
		},
		{
			MethodName: "ConfirmPrimaryProfile",
			Handler:    _MihomoAccountService_ConfirmPrimaryProfile_Handler,
		},
		{
			MethodName: "GetCredentialStatus",
			Handler:    _MihomoAccountService_GetCredentialStatus_Handler,
		},
		{
			MethodName: "ValidateCredential",
			Handler:    _MihomoAccountService_ValidateCredential_Handler,
		},
		{
			MethodName: "RefreshCredential",
			Handler:    _MihomoAccountService_RefreshCredential_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _MihomoAccountService_ListProfiles_Handler,
		},
		{
			MethodName: "GetPrimaryProfile",
			Handler:    _MihomoAccountService_GetPrimaryProfile_Handler,
		},
		{
			MethodName: "GetAuthKey",
			Handler:    _MihomoAccountService_GetAuthKey_Handler,
		},
		{
			MethodName: "GetCredentialSummary",
			Handler:    _MihomoAccountService_GetCredentialSummary_Handler,
		},
		{
			MethodName: "UpdateCredential",
			Handler:    _MihomoAccountService_UpdateCredential_Handler,
		},
		{
			MethodName: "DeleteCredential",
			Handler:    _MihomoAccountService_DeleteCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mihomo/v1/mihomo_account.proto",
}
